import {
  TabConfig,
  UniversalFormProps,
} from "@/src/components/ui/universal-form";
import {
  Attribute,
  BonusType,
  CrossoverType,
  Game,
  GameEvent,
  Gender,
  Race,
  Rarity,
  StatLevel,
} from "@prisma/client";
import { z } from "zod";

// Enum options for selects
const gameOptions = [
  { label: "Base", value: Game.Base },
  { label: "KOF", value: Game.KOF },
  { label: "Tensura", value: Game.Tensura },
  { label: "AOT", value: Game.AOT },
  { label: "Stranger Things", value: Game.StrangerThings },
  { label: "Re:Zero", value: Game.ReZero },
  { label: "Shield Hero", value: Game.ShieldHero },
  { label: "Mushoku", value: Game.Mushoku },
  { label: "Mave", value: Game.Mave },
  { label: "Overlord", value: Game.Overlord },
  { label: "TOG", value: Game.TOG },
];

const crossoverOptions = [
  { label: "Not Crossover", value: CrossoverType.NotCrossover },
  { label: "Crossover", value: CrossoverType.Crossover },
];

const raceOptions = [
  { label: "Demon", value: Race.Demon },
  { label: "Fairy", value: Race.Fairy },
  { label: "Giant", value: Race.Giant },
  { label: "Goddess", value: Race.Goddess },
  { label: "Human", value: Race.Human },
  { label: "Unknown", value: Race.Unknown },
];

const attributeOptions = [
  { label: "Dark", value: Attribute.Dark },
  { label: "HP", value: Attribute.HP },
  { label: "Light", value: Attribute.Light },
  { label: "Speed", value: Attribute.Speed },
  { label: "Strength", value: Attribute.Strength },
];

const rarityOptions = [
  { label: "LR", value: Rarity.LR },
  { label: "R", value: Rarity.R },
  { label: "SR", value: Rarity.SR },
  { label: "SSR", value: Rarity.SSR },
  { label: "UR", value: Rarity.UR },
];

const genderOptions = [
  { label: "Male", value: Gender.Male },
  { label: "Female", value: Gender.Female },
  { label: "Unknown", value: Gender.Unknown },
];

const eventOptions = [
  { label: "None", value: GameEvent.None },
  { label: "Valentine", value: GameEvent.Valentine },
  { label: "Summer", value: GameEvent.Summer },
  { label: "Christmas", value: GameEvent.Christmas },
];

const statLevelOptions = [
  { label: "Level 1", value: StatLevel.LEVEL_1 },
  { label: "Level 100", value: StatLevel.LEVEL_100 },
  { label: "True Awakening", value: StatLevel.TRUE_AWAKENING },
];

const bonusTypeOptions = [
  { label: "Attack Flat", value: BonusType.ATTACK_FLAT },
  { label: "Attack %", value: BonusType.ATTACK_PERCENTAGE },
  { label: "Defense Flat", value: BonusType.DEFENSE_FLAT },
  { label: "Defense %", value: BonusType.DEFENSE_PERCENTAGE },
  { label: "HP Flat", value: BonusType.HP_FLAT },
  { label: "HP %", value: BonusType.HP_PERCENTAGE },
  { label: "Pierce Rate Flat", value: BonusType.PIERCE_RATE_FLAT },
  { label: "Pierce Rate %", value: BonusType.PIERCE_RATE_PERCENTAGE },
  { label: "Resistance Flat", value: BonusType.RESISTANCE_FLAT },
  { label: "Resistance %", value: BonusType.RESISTANCE_PERCENTAGE },
  { label: "Regeneration Flat", value: BonusType.REGENERATION_FLAT },
  { label: "Regeneration %", value: BonusType.REGENERATION_PERCENTAGE },
  { label: "Crit Chance Flat", value: BonusType.CRIT_CHANCE_FLAT },
  { label: "Crit Chance %", value: BonusType.CRIT_CHANCE_PERCENTAGE },
  { label: "Crit Damage Flat", value: BonusType.CRIT_DAMAGE_FLAT },
  { label: "Crit Damage %", value: BonusType.CRIT_DAMAGE_PERCENTAGE },
  { label: "Crit Resistance Flat", value: BonusType.CRIT_RESISTANCE_FLAT },
  { label: "Crit Resistance %", value: BonusType.CRIT_RESISTANCE_PERCENTAGE },
  { label: "Crit Defense Flat", value: BonusType.CRIT_DEFENSE_FLAT },
  { label: "Crit Defense %", value: BonusType.CRIT_DEFENSE_PERCENTAGE },
  { label: "Recovery Rate Flat", value: BonusType.RECOVERY_RATE_FLAT },
  { label: "Recovery Rate %", value: BonusType.RECOVERY_RATE_PERCENTAGE },
  { label: "Lifesteal Flat", value: BonusType.LIFESTEAL_FLAT },
  { label: "Lifesteal %", value: BonusType.LIFESTEAL_PERCENTAGE },
];

const uniqueDisplayOptions = [
  { label: "Battle Active", value: "Battle_Active" },
  { label: "Subslot Active", value: "Subslot_Active" },
  { label: "PVP Only", value: "PVP_Only" },
  { label: "PVP Outside", value: "PVP_Outside" },
  { label: "Death Match Only", value: "Death_Match_Only" },
  { label: "Death Match Outside", value: "Death_Match_Outside" },
  { label: "All Content", value: "All_Content" },
  { label: "Demonic Beast Only", value: "Demonic_Beast_Only" },
  { label: "Demonic Beast Outside", value: "Demonic_Beast_Outside" },
];

// Tab configurations for character form
export const characterTabs: TabConfig[] = [
  {
    id: "basic",
    label: "Basic Info",
    description: "Core character identity and properties",
    columns: 3,
    fields: {
      name: {
        name: "name",
        key: "name",
        type: "text",
        label: "English Name",
        required: true,
        placeholder: "Character name in English",
      },
      jpName: {
        name: "jpName",
        key: "jpName",
        type: "text",
        label: "Japanese Name",
        required: true,
        placeholder: "Character name in Japanese",
      },
      tag: {
        name: "tag",
        key: "tag",
        type: "text",
        label: "English Tag",
        required: true,
        placeholder: "Unique tag identifier",
      },
      jpTag: {
        name: "jpTag",
        key: "jpTag",
        type: "text",
        label: "Japanese Tag",
        required: true,
        placeholder: "Unique tag in Japanese",
      },
      slug: {
        name: "slug",
        key: "slug",
        type: "text",
        label: "Slug",
        required: false,
        placeholder: "URL-friendly identifier",
      },
      imageUrl: {
        name: "imageUrl",
        key: "imageUrl",
        type: "url",
        label: "Character Image",
        required: true,
        placeholder: "https://example.com/character.png",
      },
      game: {
        name: "game",
        key: "game",
        type: "select",
        label: "Game",
        required: true,
        options: gameOptions,
        default: Game.Base,
      },
      crossover: {
        name: "crossover",
        key: "crossover",
        type: "select",
        label: "Crossover",
        required: true,
        options: crossoverOptions,
        default: CrossoverType.NotCrossover,
      },
      races: {
        name: "races",
        key: "races",
        type: "multiselect",
        label: "Race(s)",
        required: true,
        options: raceOptions,
        default: [Race.Human],
      },
      attribute: {
        name: "attribute",
        key: "attribute",
        type: "select",
        label: "Attribute",
        required: true,
        options: attributeOptions,
        default: Attribute.HP,
      },
      rarity: {
        name: "rarity",
        key: "rarity",
        type: "select",
        label: "Rarity",
        required: true,
        options: rarityOptions,
        default: Rarity.SSR,
      },
      gender: {
        name: "gender",
        key: "gender",
        type: "select",
        label: "Gender",
        required: false,
        options: genderOptions,
        default: Gender.Male,
      },
      event: {
        name: "event",
        key: "event",
        type: "select",
        label: "Event",
        required: true,
        options: eventOptions,
        default: GameEvent.None,
      },
      releaseDate: {
        name: "releaseDate",
        key: "releaseDate",
        type: "date",
        label: "Release Date",
        required: true,
      },
    },
  },
  {
    id: "details",
    label: "Character Details",
    description: "Personal information and passive skill",
    columns: 2,
    fields: {
      bloodType: {
        name: "bloodType",
        key: "bloodType",
        type: "text",
        label: "Blood Type",
        placeholder: "A+, B+, O+, etc.",
      },
      age: {
        name: "age",
        key: "age",
        type: "text",
        label: "Age",
        placeholder: "Appears to be...",
      },
      birthday: {
        name: "birthday",
        key: "birthday",
        type: "text",
        label: "Birthday",
        placeholder: "January 1",
      },
      height: {
        name: "height",
        key: "height",
        type: "text",
        label: "Height",
        placeholder: "175cm",
      },
      weight: {
        name: "weight",
        key: "weight",
        type: "text",
        label: "Weight",
        placeholder: "65kg",
      },
      location: {
        name: "location",
        key: "location",
        type: "text",
        label: "Location",
        required: true,
        placeholder: "Liones Kingdom",
      },
      CV: {
        name: "CV",
        key: "CV",
        type: "text",
        label: "CV (Voice Actor)",
        placeholder: "Voice actor name",
      },
    },
  },
  {
    id: "stats",
    label: "Stats",
    description:
      "Character combat statistics (1-3 entries with different stat levels)",
    columns: 1,
    fields: {
      stats: {
        key: "stats",
        name: "stats",
        type: "array",
        label: "Character Stats",
        required: true,
        minItems: 1,
        maxItems: 3,
        arrayConfig: {
          addButtonLabel: "Add Stat Level",
          fields: {
            level: {
              key: "level",
              name: "level",
              type: "select",
              label: "Stat Level",
              required: true,
              options: statLevelOptions,
              default: StatLevel.LEVEL_1,
            },
            combatClass: {
              key: "combatClass",
              name: "combatClass",
              type: "number",
              label: "Combat Class",
              required: true,
              placeholder: "40",
            },
            attack: {
              key: "attack",
              name: "attack",
              type: "number",
              label: "Attack",
              required: true,
              placeholder: "500",
            },
            defense: {
              key: "defense",
              name: "defense",
              type: "number",
              label: "Defense",
              required: true,
              placeholder: "300",
            },
            hp: {
              key: "hp",
              name: "hp",
              type: "number",
              label: "HP",
              required: true,
              placeholder: "2500",
            },
            pierceRate: {
              key: "pierceRate",
              name: "pierceRate",
              type: "number",
              label: "Pierce Rate",
              required: true,
              placeholder: "10",
            },
            resistance: {
              key: "resistance",
              name: "resistance",
              type: "number",
              label: "Resistance",
              required: true,
              placeholder: "10",
            },
            regeneration: {
              key: "regeneration",
              name: "regeneration",
              type: "number",
              label: "Regeneration",
              required: true,
              placeholder: "20",
            },
            critChance: {
              key: "critChance",
              name: "critChance",
              type: "number",
              label: "Crit Chance",
              required: true,
              placeholder: "10",
            },
            critDamage: {
              key: "critDamage",
              name: "critDamage",
              type: "number",
              label: "Crit Damage",
              required: true,
              placeholder: "150",
            },
            critResistance: {
              key: "critResistance",
              name: "critResistance",
              type: "number",
              label: "Crit Resistance",
              required: true,
              placeholder: "50",
            },
            critDefense: {
              key: "critDefense",
              name: "critDefense",
              type: "number",
              label: "Crit Defense",
              required: true,
              placeholder: "50",
            },
            recoveryRate: {
              key: "recoveryRate",
              name: "recoveryRate",
              type: "number",
              label: "Recovery Rate",
              required: true,
              placeholder: "100",
            },
            lifesteal: {
              key: "lifesteal",
              name: "lifesteal",
              type: "number",
              label: "Lifesteal",
              required: true,
              placeholder: "0",
            },
          },
        },
      },
    },
  },
  {
    id: "skills",
    label: "Skills",
    description: "Character active skills (2 skills with 3 ranks each)",
    columns: 1,
    fields: {
      skills: {
        key: "skills",
        name: "skills",
        type: "array",
        label: "Character Skills",

        required: true,
        fixedLength: 2,
        arrayConfig: {
          removeButtonLabel: "Remove Skill",
          addButtonLabel: "Add Skill",
          fields: {
            name: {
              key: "name",
              name: "name",
              type: "text",
              label: "Skill Name",
              required: true,
              placeholder: "Skill name",
            },
            jpName: {
              key: "jpName",
              name: "jpName",
              type: "text",
              label: "Japanese Name",
              required: true,
              placeholder: "Skill name in Japanese",
            },
            imageUrl: {
              key: "imageUrl",
              name: "imageUrl",
              type: "url",
              label: "Skill Image",
              required: true,
              placeholder: "Skill image URL",
            },
            skillRanks: {
              key: "skillRanks",
              name: "skillRanks",
              type: "array",
              label: "Skill Ranks",
              required: true,
              fixedLength: 3,
              arrayConfig: {
                fields: {
                  rank: {
                    key: "rank",
                    name: "rank",
                    type: "number",
                    label: "Rank",
                    required: true,
                    placeholder: "1",
                  },
                  description: {
                    key: "description",
                    name: "description",
                    type: "textarea",
                    label: "Description",
                    required: true,
                    placeholder: "Skill description for this rank",
                  },
                  type: {
                    key: "type",
                    name: "type",
                    type: "text",
                    label: "Type",
                    required: true,
                    placeholder: "Attack/Support/Debuff",
                  },
                },
              },
            },
          },
        },
      },
    },
  },
  {
    id: "extras",
    label: "Extra Abilities",
    description: "Optional ultimate, unity, talent, and grace abilities",
    columns: 1,
    fields: {
      // Ultimate Ability
      characterUltimate: {
        key: "characterUltimate",
        name: "characterUltimate",
        type: "object",
        label: "Character Ultimate",
        fields: {
          name: {
            key: "name",
            name: "name",
            type: "text",
            label: "Ultimate Name",
            required: true,
            placeholder: "Ultimate skill name",
          },
          jpName: {
            key: "jpName",
            name: "jpName",
            type: "text",
            label: "Japanese Name",
            required: true,
            placeholder: "Ultimate name in Japanese",
          },
          imageUrl: {
            key: "imageUrl",
            name: "imageUrl",
            type: "url",
            label: "Ultimate Image",
            required: true,
            placeholder: "Ultimate skill image URL",
          },
          description: {
            key: "description",
            name: "description",
            type: "textarea",
            label: "Ultimate Description",
            required: true,
            placeholder: "Ultimate skill description",
          },
          extraInfo: {
            key: "extraInfo",
            name: "extraInfo",
            type: "textarea",
            label: "Extra Info",
            required: false,
            placeholder: "Additional ultimate information",
          },
        },
      },
      // Combined Ultimate (Optional)
      combinedCharacterUltimate: {
        key: "combinedCharacterUltimate",
        name: "combinedCharacterUltimate",
        type: "object",
        label: "Combined Ultimate",
        fields: {
          name: {
            key: "name",
            name: "name",
            type: "text",
            label: "Combined Ultimate Name",
            required: false,
            placeholder: "Combined ultimate name",
          },
          jpName: {
            key: "jpName",
            name: "jpName",
            type: "text",
            label: "Japanese Name",
            required: false,
            placeholder: "Combined ultimate name in Japanese",
          },
          imageUrl: {
            key: "imageUrl",
            name: "imageUrl",
            type: "url",
            label: "Combined Ultimate Image",
            required: false,
            placeholder: "Combined ultimate image URL",
          },
          description: {
            key: "description",
            name: "description",
            type: "textarea",
            label: "Combined Ultimate Description",
            required: false,
            placeholder: "Combined ultimate description",
          },
          extraInfo: {
            key: "extraInfo",
            name: "extraInfo",
            type: "textarea",
            label: "Extra Info",
            required: false,
            placeholder: "Additional combined ultimate information",
          },
        },
      },
      // Passive Skill
      characterPassive: {
        key: "characterPassive",
        name: "characterPassive",
        type: "object",
        label: "Passive Skill",
        fields: {
          name: {
            key: "name",
            name: "name",
            type: "text",
            label: "Passive Name",
            required: true,
            placeholder: "Passive skill name",
          },
          jpName: {
            key: "jpName",
            name: "jpName",
            type: "text",
            label: "Japanese Name",
            required: true,
            placeholder: "Passive skill name in Japanese",
          },
          imageUrl: {
            key: "imageUrl",
            name: "imageUrl",
            type: "url",
            label: "Passive Image",
            required: true,
            placeholder: "Passive skill image URL",
          },
          description: {
            key: "description",
            name: "description",
            type: "textarea",
            label: "Passive Description",
            required: true,
            placeholder: "Description of passive effect",
          },
          ccNeeded: {
            key: "ccNeeded",
            name: "ccNeeded",
            type: "text",
            label: "CC Needed",
            required: false,
            placeholder: "CC cost to activate",
          },
          uniqueDisplay: {
            key: "uniqueDisplay",
            name: "uniqueDisplay",
            type: "multiselect",
            label: "Unique Display",
            required: false,
            options: uniqueDisplayOptions,
            default: ["All_Content"],
          },
        },
      },
      // Unity (Optional)
      characterUnity: {
        key: "characterUnity",
        name: "characterUnity",
        type: "object",
        label: "Unity",
        fields: {
          name: {
            key: "name",
            name: "name",
            type: "text",
            label: "Unity Name",
            required: false,
            placeholder: "Unity name",
          },
          jpName: {
            key: "jpName",
            name: "jpName",
            type: "text",
            label: "Japanese Name",
            required: false,
            placeholder: "Unity name in Japanese",
          },
          imageUrl: {
            key: "imageUrl",
            name: "imageUrl",
            type: "url",
            label: "Unity Image",
            required: false,
            placeholder: "Unity image URL",
          },
          description: {
            key: "description",
            name: "description",
            type: "textarea",
            label: "Unity Description",
            required: false,
            placeholder: "Unity description",
          },
          uniqueDisplay: {
            key: "uniqueDisplay",
            name: "uniqueDisplay",
            type: "multiselect",
            label: "Unique Display",
            required: false,
            options: uniqueDisplayOptions,
            default: ["All_Content"],
          },
        },
      },
      // Talent (Optional)
      characterTalent: {
        key: "characterTalent",
        name: "characterTalent",
        type: "object",
        label: "Talent",
        fields: {
          name: {
            key: "name",
            name: "name",
            type: "text",
            label: "Talent Name",
            required: false,
            placeholder: "Talent name",
          },
          jpName: {
            key: "jpName",
            name: "jpName",
            type: "text",
            label: "Japanese Name",
            required: false,
            placeholder: "Talent name in Japanese",
          },
          imageUrl: {
            key: "imageUrl",
            name: "imageUrl",
            type: "url",
            label: "Talent Image",
            required: false,
            placeholder: "Talent image URL",
          },
          description: {
            key: "description",
            name: "description",
            type: "textarea",
            label: "Talent Description",
            required: false,
            placeholder: "Talent description",
          },
          uniqueDisplay: {
            key: "uniqueDisplay",
            name: "uniqueDisplay",
            type: "multiselect",
            label: "Unique Display",
            required: false,
            options: uniqueDisplayOptions,
            default: ["All_Content"],
          },
        },
      },
      // Grace (Optional)
      characterGrace: {
        key: "characterGrace",
        name: "characterGrace",
        type: "object",
        label: "Grace",
        fields: {
          name: {
            key: "name",
            name: "name",
            type: "text",
            label: "Grace Name",
            required: false,
            placeholder: "Grace name",
          },
          jpName: {
            key: "jpName",
            name: "jpName",
            type: "text",
            label: "Japanese Name",
            required: false,
            placeholder: "Grace name in Japanese",
          },
          imageUrl: {
            key: "imageUrl",
            name: "imageUrl",
            type: "url",
            label: "Grace Image",
            required: false,
            placeholder: "Grace image URL",
          },
          description: {
            key: "description",
            name: "description",
            type: "textarea",
            label: "Grace Description",
            required: false,
            placeholder: "Grace description",
          },
          uniqueDisplay: {
            key: "uniqueDisplay",
            name: "uniqueDisplay",
            type: "multiselect",
            label: "Unique Display",
            required: false,
            options: uniqueDisplayOptions,
            default: ["All_Content"],
          },
        },
      },
    },
  },
  {
    id: "friendship",
    label: "Friendship",
    description: "Friendship rewards (5 levels for non-crossover characters)",
    columns: 1,
    disabled: false,
    fields: {
      characterFriendshipRewards: {
        key: "characterFriendshipRewards",
        name: "characterFriendshipRewards",
        type: "array",
        label: "Friendship Rewards",
        required: false,
        fixedLength: 5,
        arrayConfig: {
          addButtonLabel: "Add Friendship Level",
          removeButtonLabel: "Remove Friendship Level",
          fields: {
            level: {
              key: "level",
              name: "level",
              type: "number",
              label: "Level",
              required: true,
              placeholder: "1",
            },
            artworkUrl: {
              key: "artworkUrl",
              name: "artworkUrl",
              type: "url",
              label: "Artwork URL",
              required: false,
              placeholder: "Artwork image URL",
            },
            voiceLineText: {
              key: "voiceLineText",
              name: "voiceLineText",
              type: "textarea",
              label: "Voice Line Text",
              required: false,
              placeholder: "Voice line text",
            },
            voiceLineAudioUrl: {
              key: "voiceLineAudioUrl",
              name: "voiceLineAudioUrl",
              type: "url",
              label: "Voice Line Audio",
              required: false,
              placeholder: "Voice line audio URL",
            },
            diamondAmount: {
              key: "diamondAmount",
              name: "diamondAmount",
              type: "number",
              label: "Diamond Amount",
              required: false,
              placeholder: "1",
            },
            motionUrl: {
              key: "motionUrl",
              name: "motionUrl",
              type: "url",
              label: "Motion URL",
              required: false,
              placeholder: "Motion animation URL",
            },
            cosmeticUrl: {
              key: "cosmeticUrl",
              name: "cosmeticUrl",
              type: "url",
              label: "Cosmetic URL",
              required: false,
              placeholder: "Cosmetic item URL",
            },
            cosmeticName: {
              key: "cosmeticName",
              name: "cosmeticName",
              type: "text",
              label: "Cosmetic Name",
              required: false,
              placeholder: "Cosmetic item name",
            },
          },
        },
      },
    },
  },
  {
    id: "associations",
    label: "Associations",
    description: "Character-to-character relationship bonuses",
    columns: 1,
    fields: {
      characterAssociations: {
        key: "characterAssociations",
        name: "characterAssociations",
        type: "array",
        label: "Character Associations",
        required: false,
        arrayConfig: {
          addButtonLabel: "Add Association",
          removeButtonLabel: "Remove Association",
          fields: {
            associatedCharacterId: {
              key: "associatedCharacterId",
              name: "associatedCharacterId",
              type: "select",
              label: "Associated Character",
              required: true,
              options: [], // This will be populated dynamically
              dataSource: "characters",
            },
            bonusType: {
              key: "bonusType",
              name: "bonusType",
              type: "select",
              label: "Bonus Type",
              required: true,
              options: bonusTypeOptions,
              default: BonusType.ATTACK_FLAT,
            },
            bonusValue: {
              key: "bonusValue",
              name: "bonusValue",
              type: "number",
              label: "Bonus Value",
              required: true,
              placeholder: "10",
            },
            bonusUnit: {
              key: "bonusUnit",
              name: "bonusUnit",
              type: "text",
              label: "Bonus Unit",
              required: false,
              placeholder: "% or flat",
            },
          },
        },
      },
    },
  },
  {
    id: "gifts",
    label: "Gifts",
    description: "Items that can be given as gifts to this character",
    columns: 1,
    fields: {
      gifts: {
        key: "gifts",
        name: "gifts",
        type: "array",
        label: "Character Gifts",
        required: false,
        arrayConfig: {
          addButtonLabel: "Add Gift",
          removeButtonLabel: "Remove Gift",
          fields: {
            name: {
              key: "name",
              name: "name",
              type: "text",
              label: "Gift Name",
              required: true,
              placeholder: "Gift name",
            },
            imageUrl: {
              key: "imageUrl",
              name: "imageUrl",
              type: "url",
              label: "Gift Image",
              required: true,
              placeholder: "Gift image URL",
            },
            description: {
              key: "description",
              name: "description",
              type: "textarea",
              label: "Gift Description",
              required: true,
              placeholder: "Gift description",
            },
          },
        },
      },
    },
  },
  {
    id: "food",
    label: "Food",
    description: "Food items this character likes",
    columns: 1,
    fields: {
      food: {
        key: "food",
        name: "food",
        type: "array",
        label: "Character Food",
        required: false,
        arrayConfig: {
          addButtonLabel: "Add Food",
          removeButtonLabel: "Remove Food",
          fields: {
            name: {
              key: "name",
              name: "name",
              type: "text",
              label: "Food Name",
              required: true,
              placeholder: "Food name",
            },
            imageUrl: {
              key: "imageUrl",
              name: "imageUrl",
              type: "url",
              label: "Food Image",
              required: true,
              placeholder: "Food image URL",
            },
            effect: {
              key: "effect",
              name: "effect",
              type: "textarea",
              label: "Food Effect",
              required: false,
              placeholder: "Food effect description",
            },
            mealId: {
              key: "mealId",
              name: "mealId",
              type: "number",
              label: "Meal ID",
              required: false,
              placeholder: "1",
            },
          },
        },
      },
    },
  },
  {
    id: "holyrelic",
    label: "Holy Relic",
    description: "Holy relic associated with this character",
    columns: 1,
    fields: {
      holyRelicId: {
        key: "holyRelicId",
        name: "holyRelicId",
        type: "select",
        label: "Holy Relic",
        required: false,
        options: [], // This will be populated dynamically
        dataSource: "holyRelics",
      },
    },
  },
];

// Function to get dynamic character form props
export function getCharacterFormProps(
  character?: any,
  allCharacters?: any[],
  allGifts?: any[],
  allFood?: any[],
  allHolyRelics?: any[],
): UniversalFormProps<any> {
  return {
    schema: z.object({}), // This will be replaced with actual character schema
    defaultValues: character,
    action: async (values: any) => {
      // This will use the server actions we created
      const { createCharacter, updateCharacter } = await import(
        "../server-actions"
      );

      if (character?.id) {
        return await updateCharacter(character.id, values);
      } else {
        return await createCharacter(values);
      }
    },
    tabs: characterTabs,
    layout: "character",
    multiColumn: true,
    dataSources: {
      characters: allCharacters || [],
      gifts: allGifts || [],
      food: allFood || [],
      holyRelics: allHolyRelics || [],
    },
    submitText: character?.id ? "Update Character" : "Create Character",
    onSuccess: (message: any) => {
      // Handle success - could show toast, redirect, etc.
      console.log("Character form success:", message);
    },
    onError: (error: any) => {
      // Handle error - could show toast, log error, etc.
      console.error("Character form error:", error);
    },
  };
}
