import { Character } from "@/types/character";
import { Games } from "@/types/game";
import { Attributes } from "../../types/attributes";
import { Crossovers } from "../../types/crossover";
import { Races } from "../../types/race";
import { Rarities } from "../../types/rarity";

export const characters: Character[] = [
  {
    name: "Queen Diane",
    slug: "queen_diane",
    tag: "Love's Messenger",
    jpName: "ディアンヌ",
    jpTag: "恋の伝令",
    stats: {
      combatClass_Cp: 3327,
      attack: 520,
      defense: 752,
      hp: 1254,
      pierceRate: "20%",
      resistance: "20%",
      regeneration: "20%",
      critChance: "20%",
      critDamage: "20%",
      critResistance: "20%",
      critDefense: "20%",
      recoveryRate: "20%",
      lifesteal: "20%",
    },
    imageUrl:
      "https://gcdatabase.com/images/characters/queen_diane/ssrg_portrait.png",
    attribute: Attributes.HP,
    rarity: Rarities.SSR,
    race: Races.Giant,
    crossover: Crossovers.NotCrossover,
    game: Games.Base,
    associations: [
      {
        slug: "alioni",
        bonus: "HP +5%",
      },
      {
        slug: "jue_viole_grace",
        bonus: "Attack +280",
      },
    ],
  },
  {
    name: "Queen Diane",
    slug: "queen_diane_2",
    tag: "Waves of the Earth",
    jpTag: "永遠の約束",
    jpName: "聖騎士 ディアンヌ",
    stats: {
      combatClass_Cp: 0,
      attack: 0,
      defense: 0,
      hp: 0,
      pierceRate: "",
      resistance: "",
      regeneration: "",
      critChance: "",
      critDamage: "",
      critResistance: "",
      critDefense: "",
      recoveryRate: "",
      lifesteal: "",
    },
    imageUrl:
      "https://gcdatabase.com/images/characters/queen_diane/ssrr_portrait.png",
    attribute: Attributes.Strength,
    game: Games.Base,
    rarity: Rarities.SSR,
    race: Races.Giant,
    crossover: Crossovers.NotCrossover,
  },
  {
    name: "Jue Viole Grace",
    slug: "jue_viole_grace",
    tag: "Slayer Candidate",
    jpTag: "ジュ・ビオレ・グレイス",
    jpName: "スレイヤー候補",
    stats: {
      combatClass_Cp: 0,
      attack: 0,
      defense: 0,
      hp: 0,
      pierceRate: "",
      resistance: "",
      regeneration: "",
      critChance: "",
      critDamage: "",
      critResistance: "",
      critDefense: "",
      recoveryRate: "",
      lifesteal: "",
    },
    imageUrl:
      "https://gcdatabase.com/images/characters/jyu_viole_grace/ssrr_portrait.png",
    attribute: Attributes.Strength,
    rarity: Rarities.SSR,
    race: Races.Human,
    crossover: Crossovers.Crossover,
    game: Games.TOG,
  },
  {
    name: "Alioni",
    slug: "alioni",
    tag: "Beard Of The Mountain Cat",
    jpTag: "〈山猫の髭〉騎士団",
    jpName: "団員 アリオーニ",
    stats: {
      combatClass_Cp: 0,
      attack: 0,
      defense: 0,
      hp: 0,
      pierceRate: "",
      resistance: "",
      regeneration: "",
      critChance: "",
      critDamage: "",
      critResistance: "",
      critDefense: "",
      recoveryRate: "",
      lifesteal: "",
    },
    imageUrl:
      "https://gcdatabase.com/images/characters/alioni/rg_portrait.webp",
    attribute: Attributes.HP,
    rarity: Rarities.R,
    race: Races.Human,
    crossover: Crossovers.NotCrossover,
    game: Games.Base,
    holyRelic: [
      {
        name: "Double-edged Sword of the Einherjar",
        imageUrl: "https://gcdatabase.com/images/relics/alioni_relic.png",
        effect: "Decreases the hero’s damage taken from enemies by 40%.",
        stats: [
          {
            attack: "+140",
            defense: "+300",
            hp: "+3100",
          },
        ],
      },
    ],
  },
  {
    name: "Eren Yeager",
    slug: "eren_yeager",
    tag: "Titan Form",
    jpName: "エレン・イェーガー",
    jpTag: "巨人化能力",
    stats: {
      combatClass_Cp: 0,
      attack: 0,
      defense: 0,
      hp: 0,
      pierceRate: "",
      resistance: "",
      regeneration: "",
      critChance: "",
      critDamage: "",
      critResistance: "",
      critDefense: "",
      recoveryRate: "",
      lifesteal: "",
    },
    imageUrl:
      "https://gcdatabase.com/images/characters/eren/ssrg_portrait.webp",
    attribute: Attributes.HP,
    game: Games.AOT,
    rarity: Rarities.SSR,
    race: Races.HumanGiant,
    crossover: Crossovers.Crossover,
  },
];

export default characters;
